package io.github.dumijdev.jambaui.core.style;

import java.util.Map;

public interface Style extends Iterable<Map.Entry<String, Object>>{
    Style setBackgroundColor(String color);
    String getBackgroundColor();
    Style setFontColor(String color);
    String getFontColor();
    Style setFontSize(int size);
    int getFontSize();
    Style setFontFamily(String family);
    String getFontFamily();
    Style setFontStyle(String style);
    String getFontStyle();
    Style setFontWeight(float weight);
    float getFontWeight();
    Style setHeight(double height);
    double getHeight();
    Style setWidth(double width);
    double getWidth();
    Style setLineSpacing(int spacing);
    int getLineSpacing();
    Style setTitle(String title);
    String getTitle();
    Style set(String key, Object value);
    Object get(String key);
    Style set(Style style);
    Style remove(String key);
    Style setMargin(String margin);
    String getMargin();
    Style setMarginTop(int marginTop);
    int getMarginTop();
    Style setMarginBottom(int marginBottom);
    int getMarginBottom();
    Style setMarginLeft(int marginLeft);
    int getMarginLeft();
    Style setMarginRight(int marginRight);
    int getMarginRight();
    Style setPadding(int padding);
    int getPadding();
    Style setPaddingTop(int paddingTop);
    int getPaddingTop();
    Style setPaddingBottom(int paddingBottom);
    int getPaddingBottom();
    Style setPaddingLeft(int paddingLeft);
    int getPaddingLeft();
    Style setPaddingRight(int paddingRight);
    int getPaddingRight();
    Style setBorder(int border);
    int getBorder();
    Style setBorderTop(int borderTop);
    int getBorderTop();
    Style setBorderBottom(int borderBottom);
    int getBorderBottom();
    Style setBorderLeft(int borderLeft);
    int getBorderLeft();
    Style setBorderRight(int borderRight);
    int getBorderRight();
    Style setBorderRadius(int borderRadius);
    int getBorderRadius();
    Style setBorderColor(String color);
    String getBorderColor();
    Style setBorderWidth(int borderWidth);
    int getBorderWidth();
    Style setBorderStyle(String style);
    String getBorderStyle();
    Style setDisplay(String display);
    String getDisplay();
    Style setFont(String font);
    String getFont();
    Style setFlexDirection(String flexDirection);
    String getFlexDirection();
    Style setFlexWrap(String flexWrap);
    String getFlexWrap();
    Style setAlign(String align);
    String getAlign();
    Style setAlignItems(String alignItems);
    String getAlignItems();
}
